Idea-Hive/server

.gitignore, src/main/java/Idea/Idea_Hive/auth/service/CustomOauth2UserService.java, src/main/java/Idea/Idea_Hive/auth/service/JwtProvider.java, src/main/java/Idea/Idea_Hive/member/controller/AuthController.java, src/main/java/Idea/Idea_Hive/member/entity/repository/MemberJpaRepo.java, src/main/java/Idea/Idea_Hive/project/entity/Project.java, src/main/java/Idea/Idea_Hive/project/entity/ProjectFile.java, src/main/java/Idea/Idea_Hive/security/SecurityConfig.java, src/main/resources/application.yaml
- SecurityConfig 파일에 CORS 세팅 추가
=> feat: cors setting

.gitignore, build.gradle, docker/redis/docker-compose.yml, docker/redis/redis.conf, src/main/java/Idea/Idea_Hive/auth/controller/AuthController.java, src/main/java/Idea/Idea_Hive/email/controller/EmailController.java, src/main/java/Idea/Idea_Hive/email/service/EmailAuthService.java, src/main/java/Idea/Idea_Hive/member/controller/MemberController.java, src/main/java/Idea/Idea_Hive/redis/RedisConfig.java, src/main/resources/application.yaml
- 필요 라이브러리 추가 (build.gradle)
- OAuth github/google 소셜 로그인 (초안)
본문(body):
- Redis 연동 및 docker-compose 파일 작성
- 메일 인증 및 검증 api 작성
푸터(footer):
- 생략
ex. 노션, Figma, 이슈 링크
-   ex. 뭐뭐 변경했다~
-   ex. #56 [Feat] 이슈이름
-   ex. 뭐뭐 코드 리뷰나 확인좀 해주라~~
=> 제목(subject):

.env
=> chore: env file delete

src/main/java/Idea/Idea_Hive/project/controller/ProjectController.java, src/main/java/Idea/Idea_Hive/project/dto/response/ProjectResponseDto.java, src/main/java/Idea/Idea_Hive/project/dto/response/ProjectSearchResponse.java, src/main/java/Idea/Idea_Hive/project/entity/Project.java, src/main/java/Idea/Idea_Hive/project/entity/repository/ProjectRepository.java, src/main/java/Idea/Idea_Hive/project/entity/repository/ProjectRepositoryCustom.java, src/main/java/Idea/Idea_Hive/project/entity/repository/ProjectRepositoryImpl.java, src/main/java/Idea/Idea_Hive/project/service/ProjectService.java, src/main/java/Idea/Idea_Hive/querydsl/QuerydslConfig.java
- 해시태그, 프로젝트 제목, 전체|신규모집|추가모집 으로 필터링 및 검색 기능 개발
=> chore: project search with hashtagid, keyword, recruitType

src/main/java/Idea/Idea_Hive/auth/controller/AuthController.java, src/main/java/Idea/Idea_Hive/auth/handler/CustomOAuth2SuccessHandler.java, src/main/java/Idea/Idea_Hive/project/entity/Project.java, src/main/java/Idea/Idea_Hive/redis/RedisConfig.java, src/main/java/Idea/Idea_Hive/redis/RedisDao.java
ex. 노션, Figma, 이슈 링크
-   Redis Client 작업 진행 중
-   ex. #56 [Feat] 이슈이름
-   ex. 뭐뭐 코드 리뷰나 확인좀 해주라~~
=> Redis Client 작업 진행 중

src/main/java/Idea/Idea_Hive/exception/handler/GlobalExceptionHandler.java, src/main/java/Idea/Idea_Hive/exception/handler/custom/HashtagAlreadyExistsException.java, src/main/java/Idea/Idea_Hive/exception/handler/custom/SkillStackAlreadyExistsException.java, src/main/java/Idea/Idea_Hive/skillstack/controller/SkillStackController.java, src/main/java/Idea/Idea_Hive/skillstack/entity/SkillStack.java, src/main/java/Idea/Idea_Hive/skillstack/service/SkillStackService.java
body : Hashtag → SkillStack 변경 과정에서 발생한 함수명 및 주석 불일치 수정
ex. 노션, Figma, 이슈 링크
-   ex. 뭐뭐 변경했다~
-   ex. #56 [Feat] 이슈이름
-   ex. 뭐뭐 코드 리뷰나 확인좀 해주라~~
=> subject : SkillStack 연관 함수 이름 및 주석 수정

src/main/java/Idea/Idea_Hive/project/controller/ProjectController.java, src/main/java/Idea/Idea_Hive/project/dto/request/ProjectCreateRequest.java, src/main/java/Idea/Idea_Hive/project/entity/Project.java, src/main/java/Idea/Idea_Hive/project/entity/ProjectDetail.java, src/main/java/Idea/Idea_Hive/project/entity/ProjectMember.java, src/main/java/Idea/Idea_Hive/project/entity/ProjectMemberId.java, src/main/java/Idea/Idea_Hive/project/entity/repository/ProjectMemberRepository.java, src/main/java/Idea/Idea_Hive/project/entity/repository/SkillStackRepository.java, src/main/java/Idea/Idea_Hive/project/service/ProjectService.java, src/main/java/Idea/Idea_Hive/security/SecurityConfig.java
=> feat: project create API

src/main/java/Idea/Idea_Hive/project/controller/ProjectController.java, src/main/java/Idea/Idea_Hive/project/entity/repository/ProjectRepositoryCustom.java, src/main/java/Idea/Idea_Hive/project/entity/repository/ProjectRepositoryImpl.java, src/main/java/Idea/Idea_Hive/project/service/ProjectService.java, src/main/resources/application.yaml
[DB 변경]
-  h2 -> postgreSQL로 변경
- 추후 DB의 username과 password 변경 필요
[프로젝트 탐색]
- 정렬 기준에서 최신순과 마감임박순으로 정렬하는 기능 추가
=> Develop project search

src/main/java/Idea/Idea_Hive/IdeaHiveApplication.java, src/main/resources/application.yaml
=> chore: .env setting

src/main/java/Idea/Idea_Hive/security/SecurityConfig.java
- securityConfig에서 h2 관련 설정 제거
- 프로젝트 탐색 시, 토큰 없이도 접근 가능하도록 설정
=> chore: security setting

src/main/java/Idea/Idea_Hive/TaskMateApplication.java, src/main/java/Idea/Idea_Hive/project/controller/ProjectController.java, src/main/java/Idea/Idea_Hive/project/dto/response/ProjectResponseDto.java, src/main/java/Idea/Idea_Hive/project/dto/response/ProjectSearchResponse.java, src/main/java/Idea/Idea_Hive/project/entity/Project.java, src/main/java/Idea/Idea_Hive/project/entity/ProjectMember.java, src/main/java/Idea/Idea_Hive/project/entity/repository/ProjectRepositoryCustom.java, src/main/java/Idea/Idea_Hive/project/entity/repository/ProjectRepositoryImpl.java, src/main/java/Idea/Idea_Hive/project/service/ProjectService.java
- 프로젝트 탐색 시 페이지네이션 기능 추가(12개씩)
=> chore: search paging 기능 추가

src/main/java/Idea/Idea_Hive/member/controller/MemberController.java, src/main/java/Idea/Idea_Hive/member/entity/dto/response/MemberInfoResponse.java, src/main/java/Idea/Idea_Hive/member/service/MemberService.java
현재 로그인한 Member 정보 조회 api 개발
/api/member/info
=> feat : 현재 로그인한 유저 정보 조회 api 개발

src/main/java/Idea/Idea_Hive/auth/handler/CustomOAuth2SuccessHandler.java, src/main/java/Idea/Idea_Hive/member/service/MemberService.java
-   이메일 회원가입 - sns 회원가입 간 이메일 중복 예외 처리
=> fix: 이메일 회원가입 - 소셜 로그인 회원가입 중복 예외 처리

src/main/java/Idea/Idea_Hive/project/controller/ProjectController.java, src/main/java/Idea/Idea_Hive/project/controller/ProjectCreateController.java, src/main/java/Idea/Idea_Hive/project/controller/ProjectSearchController.java, src/main/java/Idea/Idea_Hive/project/dto/request/ProjectApplyDecisionRequest.java, src/main/java/Idea/Idea_Hive/project/dto/request/ProjectApplyRequest.java, src/main/java/Idea/Idea_Hive/project/dto/request/ProjectIdAndMemberIdDto.java, src/main/java/Idea/Idea_Hive/project/dto/request/ProjectLikeRequest.java, src/main/java/Idea/Idea_Hive/project/entity/Project.java, src/main/java/Idea/Idea_Hive/project/entity/ProjectApplications.java, src/main/java/Idea/Idea_Hive/project/entity/ProjectMember.java, src/main/java/Idea/Idea_Hive/project/entity/repository/ProjectApplicationsRepository.java, src/main/java/Idea/Idea_Hive/project/service/ProjectService.java, src/main/resources/application.yaml
[프로젝트 상세 API 개발]
- 아이디어 열람
- 지원하기
- 지원자 거절/확정/확정 취소
- 지원하기 수정
- 지원 취소
=> Develop project apply

src/main/java/Idea/Idea_Hive/project/service/ProjectService.java, src/main/resources/application.yaml
=> Develop project apply fix

src/main/java/Idea/Idea_Hive/member/entity/dto/request/SignUpRequest.java, src/main/java/Idea/Idea_Hive/project/controller/ProjectManageController.java, src/main/java/Idea/Idea_Hive/project/entity/repository/manage/ProjectManageRepositoryCustom.java, src/main/java/Idea/Idea_Hive/project/entity/repository/manage/ProjectManageRepositoryCustomImpl.java, src/main/java/Idea/Idea_Hive/project/service/ProjectManageService.java, src/main/java/Idea/Idea_Hive/task/controller/TaskController.java
project id기준 프로젝트 참여 멤버 조회 api 개발
=> feature: project id기준 프로젝트 참여 멤버 조회 api 개발

src/main/java/Idea/Idea_Hive/member/entity/dto/request/SignUpRequest.java, src/main/java/Idea/Idea_Hive/member/service/MemberService.java
=> fix: 이메일 회원가입 시 이름 추가

build.gradle, src/main/java/Idea/Idea_Hive/config/S3Config.java, src/main/java/Idea/Idea_Hive/test/TestController.java, src/main/resources/application.yaml
=> s3 connection test

src/main/java/Idea/Idea_Hive/file/service/FileStorageService.java
=> chore: s3 connection

src/main/java/Idea/Idea_Hive/task/service/TaskService.java
fix: 과제 담당자 변경 API 수정 - 빈 값 허용
=> fix: 과제 담당자 변경 API 수정 - 빈 값 허용

src/main/java/Idea/Idea_Hive/project/controller/ProjectManageController.java, src/main/java/Idea/Idea_Hive/project/entity/repository/manage/ProjectManageRepositoryCustom.java, src/main/java/Idea/Idea_Hive/project/entity/repository/manage/ProjectManageRepositoryCustomImpl.java, src/main/java/Idea/Idea_Hive/project/service/ProjectManageService.java
feature: 마이페이지 > 내 프로젝트 전체 목록 조회 API
- ProjectManageController.getAllProject()
- ProjectManagerService.getAllProjectList()
- ProjectManageRepositoryCustom.findProjectByMemberIdWithPage()
=> feature: 마이페이지 > 내 프로젝트 전체 목록 조회 API

src/main/java/Idea/Idea_Hive/file/service/FileStorageService.java, src/main/java/Idea/Idea_Hive/file/service/LocalFileStorageService.java, src/main/java/Idea/Idea_Hive/file/service/ProdFileStorageService.java, src/main/java/Idea/Idea_Hive/task/controller/TaskController.java, src/main/java/Idea/Idea_Hive/task/dto/response/DownloadFileResponse.java, src/main/java/Idea/Idea_Hive/task/entity/Task.java, src/main/resources/application.yaml
- Task Entity 필드 추가 : originalFileName (업로드할 원본 파일 이름)
- LocalFileStorageService, ProdFileStorageService 구현
=> feature: 과제 파일 업로드 및 다운로드 API 구현 (prod, local 모두)

src/main/java/Idea/Idea_Hive/config/S3Config.java
-   s3Config에서 AmazonS3Client 타입 변경
=> hotfix: AmazonS3Client type change

src/main/java/Idea/Idea_Hive/project/entity/repository/manage/ProjectManageRepositoryCustomImpl.java
ProjectManageRespository에 문자 하나 잘못 들어가서 에러
=> 에러 (문자 하나 잘못 들어감 ..)

src/main/java/Idea/Idea_Hive/auth/handler/CustomOAuth2SuccessHandler.java, src/main/resources/application.yaml
=> fix: oauth domain setting

src/main/java/Idea/Idea_Hive/task/dto/response/TaskResponse.java
=> hotfix: TaskResponse name fix

src/main/java/Idea/Idea_Hive/auth/controller/AuthController.java
=> hotfix: refreshtoken cookie delete

src/main/java/Idea/Idea_Hive/auth/controller/AuthController.java
=> hotfix: logout fix

src/main/java/Idea/Idea_Hive/auth/service/CustomOauth2UserService.java
=> hotfix: github uri check

src/main/java/Idea/Idea_Hive/file/service/ProdFileStorageService.java, src/main/java/Idea/Idea_Hive/task/dto/response/TaskResponse.java, src/main/java/Idea/Idea_Hive/task/entity/Task.java
=> hotfix: file upload entity fix

src/main/java/Idea/Idea_Hive/file/service/ProdFileStorageService.java, src/main/java/Idea/Idea_Hive/task/controller/TaskController.java
=> hotfix: upload시 contentDisposition을 설정하여 다운로드 할 수 있도록 수정

src/main/java/Idea/Idea_Hive/project/controller/ProjectManageController.java, src/main/java/Idea/Idea_Hive/project/dto/response/ProjectSubmitResponse.java, src/main/java/Idea/Idea_Hive/project/service/ProjectManageService.java
-   제출 안되었을 경우 리스트에 제출안된 과제 id return
=> hotfix: 제출 안되었을 경우 리스트에 제출안된 과제 id return
